### ISSUE TITLE
Allow sending requestBody as InputStream instead of byte[]

### ISSUE THREAD

**Issue by dekelpilli** [davidmoten/aws-lightweight-client-java#119]
This is something that's supported in other S3-compatible clients (e.g. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/AbstractPutObjectRequest.java#L912, https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/PutObjectArgs.java#L65) as it enables uploading large objects without needing to store them fully in memory.

If you're open to it, I could make a PR with this change.

**Comment by davidmoten** [comment]
This does what you want: https://github.com/davidmoten/aws-lightweight-client-java/wiki/Recipes#multipart-upload-a-file

**Comment by dekelpilli** [comment]
Oh, my bad, I wasn't aware that API existed. Thanks for the quick response!
