### ISSUE TITLE
Fails to load credentials when SnapStart is activated

### ISSUE THREAD

**Issue by andreaselias** [davidmoten/aws-lightweight-client-java#191]
The following doc states that when SnapStart is activated the AWS credentials should work a little different. When I tried to use the libary as is with the SnapStart activated I got an error "argument cannot be null" which is a result of the checkNotNull method of the Preconditions class.

https://docs.aws.amazon.com/lambda/latest/dg/snapstart-activate.html

> When SnapStart is activated, the Lambda runtime automatically uses the container credentials (AWS_CONTAINER_CREDENTIALS_FULL_URI and AWS_CONTAINER_AUTHORIZATION_TOKEN) instead of the access key environment variables. This prevents credentials from expiring before the function is restored.

It would be great if you could make it work with SnapStart. For now, as a workaround I am using without the SnapStart.

**Comment by davidmoten** [comment]
Thanks for the report, I'll get support for that sorted

**Comment by davidmoten** [comment]
See this [PR](https://github.com/davidmoten/aws-lightweight-client-java/pull/194)

**Comment by davidmoten** [comment]
Enhancement released in [0.1.19](https://github.com/davidmoten/aws-lightweight-client-java/releases/tag/0.1.19)
